-- Create the products table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  slug text unique not null,
  title text not null,
  description text,
  image text not null,
  price numeric not null,
  category text not null check (category in ('gadget', 'sticks')),
  in_stock boolean default true,
  badges jsonb default '{}'::jsonb,
  attributes jsonb default '{}'::jsonb,
  brand text
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- Create policy to allow public read access
create policy "Allow public read access"
  on public.products
  for select
  to public
  using (true);

-- Create policy to allow service role to insert/update (implicit, but good to know)
-- Service role has bypass RLS, so no specific policy needed for migration script if using service key.
