-- ============================================================================
-- 24iqos — Supabase schema (reference)
-- ----------------------------------------------------------------------------
-- Reconciled against the live database on 2026-08-31 via the PostgREST/OpenAPI
-- introspection (columns, types, NOT NULL, PK/FK are verified). Column DEFAULTS,
-- CHECK constraints, indexes and RLS policies are reconstructed to match
-- observed application behaviour and standard Supabase conventions — confirm
-- against the live DB (`\d+ <table>`) before treating this file as canonical.
--
-- NOTE: The `products.category` value 'accessories' also exists in the live DB
-- but is intentionally handled on a separate feature branch and is NOT modelled
-- here yet.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- products — catalog items (devices, sticks, water)
-- ----------------------------------------------------------------------------
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  slug text unique not null,
  title text not null,
  description text,
  image text[],                                  -- array of image URLs
  price numeric not null,
  category text not null check (category in ('gadget', 'sticks', 'water')),
  in_stock boolean default true,
  badges jsonb default '{}'::jsonb,
  attributes jsonb default '{}'::jsonb,
  brand text
);

alter table public.products enable row level security;

create policy "Allow public read access"
  on public.products
  for select
  to public
  using (true);

-- ----------------------------------------------------------------------------
-- orders — one row per placed order (checkout) or trade-in request
-- ----------------------------------------------------------------------------
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_name text not null,
  user_email text not null,
  user_phone text not null,
  user_message text,                             -- optional free-text comment
  total_amount numeric not null,                 -- final amount payable
  status text default 'pending',                 -- set by the application
  order_type text not null default 'purchase'    -- 'purchase' | 'trade_in'
    check (order_type in ('purchase', 'trade_in')),
  discount numeric not null default 0,           -- amount discounted from subtotal
  items jsonb not null default '[]'::jsonb,      -- self-contained line snapshot
  metadata jsonb not null default '{}'::jsonb    -- order-type-specific extras
);

create index if not exists orders_order_type_idx on public.orders (order_type);

alter table public.orders enable row level security;

-- ----------------------------------------------------------------------------
-- order_items — line items for a purchase order (FK -> products)
-- ----------------------------------------------------------------------------
create table public.order_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id bigint not null references public.orders (id) on delete cascade,
  product_id bigint not null references public.products (id),
  quantity integer not null,
  price_at_time numeric not null                 -- unit price snapshot at order time
);

alter table public.order_items enable row level security;

-- ----------------------------------------------------------------------------
-- contact_messages — contact form submissions
-- ----------------------------------------------------------------------------
create table public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text not null,
  message text not null,
  status text default 'new'                       -- set by the application
);

alter table public.contact_messages enable row level security;

-- ============================================================================
-- RLS model (no user accounts — every visitor is an anonymous guest):
--   * products          — RLS on, public SELECT (catalog is public).
--   * orders            — RLS on, NO anon policies. Writes go through server
--   * order_items         actions using the SERVICE ROLE key (lib/supabase-admin.ts),
--                         which bypasses RLS. anon cannot read or write directly.
--   * contact_messages  — RLS on, anon INSERT allowed (guests submit the contact
--                         form), no anon SELECT.
-- See supabase/migrations/20260831_lock_down_orders_rls.sql.
-- ============================================================================
