-- Step 1: Update Check Constraint to allow 'accessories'
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_category_check;
ALTER TABLE products ADD CONSTRAINT products_category_check CHECK (category IN ('gadget', 'sticks', 'water', 'accessories'));

-- Step 2: Insert All Accessory Products with live Supabase Storage URLs
INSERT INTO products (slug, title, description, price, category, in_stock, brand, image, badges, attributes)
VALUES
(
  'iqos-iluma-i-x-seletti-nabor-kolets-1001',
  'IQOS ILUMA i x Seletti Набор колец',
  'Официальный аксессуар IQOS ILUMA i x Seletti Набор колец для IQOS ILUMA i.',
  7100,
  'accessories',
  true,
  'IQOS x SELETTI',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-ring-set/1.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-ring-set/2.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-ring-set/3.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","type":"Колпачки","compatibility":"IQOS ILUMA i","hex":"linear-gradient(135deg, #BAAE75 0%, #EADAA2 50%, #080905 100%)"}'::jsonb
),
(
  'iqos-iluma-i-prime-x-seletti-kryshka-nakladka-seletti-gradient-black-gold-3-1002',
  'IQOS ILUMA i Prime x Seletti Крышка-накладка - Seletti Gradient Black Gold',
  'Официальный аксессуар IQOS ILUMA i Prime x Seletti Крышка-накладка - Seletti Gradient Black Gold 3 для IQOS ILUMA i PRIME.',
  14200,
  'accessories',
  true,
  'IQOS x SELETTI',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-prime-cover/gradient-black-gold-1.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-prime-cover/gradient-black-gold-2.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Золотой","colorVariantName":"Seletti Gradient Black Gold","line":"IQOS ILUMA i Prime x Seletti Крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#876F38"}'::jsonb
),
(
  'iqos-iluma-i-prime-x-seletti-kryshka-nakladka-seletti-scallop-white-gold-1-1003',
  'IQOS ILUMA i Prime x Seletti Крышка-накладка - Seletti Scallop White Gold',
  'Официальный аксессуар IQOS ILUMA i Prime x Seletti Крышка-накладка - Seletti Scallop White Gold 1 для IQOS ILUMA i PRIME.',
  14200,
  'accessories',
  true,
  'IQOS x SELETTI',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-prime-cover/scallop-white-gold-1.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-prime-cover/scallop-white-gold-2.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-prime-cover/scallop-white-gold-3.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-prime-cover/scallop-white-gold-4.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Золотой","colorVariantName":"Seletti Scallop White Gold","line":"IQOS ILUMA i Prime x Seletti Крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#D2D2D2"}'::jsonb
),
(
  'panel-dlya-iqos-iluma-i-x-seletti-seletti-gradient-black-1-1007',
  'Панель для IQOS ILUMA i x Seletti - Seletti Gradient Black',
  'Официальный аксессуар Панель для IQOS ILUMA i x Seletti - Seletti Gradient Black 1 для IQOS ILUMA i.',
  8500,
  'accessories',
  true,
  'IQOS x SELETTI',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-panel/gradient-black-1.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-panel/gradient-black-2.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-panel/gradient-black-3.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Черный","colorVariantName":"Seletti Gradient Black","line":"Панель для IQOS ILUMA i x Seletti","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#876F38"}'::jsonb
),
(
  'panel-dlya-iqos-iluma-i-x-seletti-seletti-zagged-golden-1-1010',
  'Панель для IQOS ILUMA i x Seletti - Seletti Zagged Golden',
  'Официальный аксессуар Панель для IQOS ILUMA i x Seletti - Seletti Zagged Golden 1 для IQOS ILUMA i.',
  8500,
  'accessories',
  true,
  'IQOS x SELETTI',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-panel/zagged-golden-1.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/seletti-panel/zagged-golden-2.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Золотой","colorVariantName":"Seletti Zagged Golden","line":"Панель для IQOS ILUMA i x Seletti","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#D3AF37"}'::jsonb
),
(
  'nabor-kolets-iqos-iluma-i-chromo-matic-1012',
  'Набор колец IQOS ILUMA i - Chromo Matic',
  'Официальный аксессуар Набор колец IQOS ILUMA i - Chromo Matic для IQOS ILUMA i.',
  5300,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/chromo-matic-ring-set/chromo-matic.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","type":"Колпачки","compatibility":"IQOS ILUMA i","hex":"linear-gradient(135deg, #01E5E3 0%, #AD2E2E 50%, #A3A1A4 100%)","line":"Набор колец IQOS ILUMA i","colorVariantName":"Chromo Matic"}'::jsonb
),
(
  'nabor-kolets-iqos-iluma-i-shimmering-shades-1013',
  'Набор колец IQOS ILUMA i - Shimmering Shades',
  'Официальный аксессуар Набор колец IQOS ILUMA i - Shimmering Shades для IQOS ILUMA i.',
  4900,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/shimmering-shades-ring-set/shimmering-shades.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Фиолетовый","type":"Колпачки","compatibility":"IQOS ILUMA i","hex":"linear-gradient(135deg, #E1D0DA 0%, #E95A97 50%, #D0E762 100%)","line":"Набор колец IQOS ILUMA i","colorVariantName":"Shimmering Shades"}'::jsonb
),
(
  'iqos-iluma-i-prime-metallik-kryshka-nakladka-bold-blue-1014',
  'IQOS ILUMA i PRIME Металлик крышка-накладка - Bold Blue',
  'Официальный аксессуар IQOS ILUMA i PRIME Металлик крышка-накладка - Bold Blue для IQOS ILUMA i PRIME.',
  9900,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-prime-metallic-cover/bold-blue.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Синий","colorVariantName":"Bold Blue","line":"IQOS ILUMA i PRIME Металлик крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#2563EB"}'::jsonb
),
(
  'iqos-iluma-i-prime-metallik-kryshka-nakladka-easy-green-1015',
  'IQOS ILUMA i PRIME Металлик крышка-накладка - Easy Green',
  'Официальный аксессуар IQOS ILUMA i PRIME Металлик крышка-накладка - Easy Green для IQOS ILUMA i PRIME.',
  9900,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-prime-metallic-cover/easy-green.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Зеленый","colorVariantName":"Easy Green","line":"IQOS ILUMA i PRIME Металлик крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#059669"}'::jsonb
),
(
  'iqos-iluma-i-prime-kryshka-nakladka-vibrant-orange-1016',
  'IQOS ILUMA i PRIME Крышка-накладка - Vibrant Orange',
  'Официальный аксессуар IQOS ILUMA i PRIME Крышка-накладка - Vibrant Orange для IQOS ILUMA i PRIME.',
  8500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-prime-cover/vibrant-orange.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Золотой","colorVariantName":"Vibrant Orange","line":"IQOS ILUMA i PRIME Крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#EA580C"}'::jsonb
),
(
  'iqos-iluma-i-prime-kryshka-nakladka-zest-yellow-1017',
  'IQOS ILUMA i PRIME Крышка-накладка - Zest Yellow',
  'Официальный аксессуар IQOS ILUMA i PRIME Крышка-накладка - Zest Yellow для IQOS ILUMA i PRIME.',
  8500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-prime-cover/zest-yellow.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Золотой","colorVariantName":"Zest Yellow","line":"IQOS ILUMA i PRIME Крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#DCDE3F"}'::jsonb
),
(
  'alyuminevaya-panel-dlya-iqos-iluma-i-1018',
  'Алюминевая панель для IQOS ILUMA i',
  'Официальный аксессуар Алюминевая панель для IQOS ILUMA i для IQOS ILUMA i.',
  6300,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-aluminum-panel/brisk-blue.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#0B45C7"}'::jsonb
),
(
  'panel-dlya-iqos-iluma-i-chill-blue-1019',
  'Панель для IQOS ILUMA i - Chill Blue',
  'Официальный аксессуар Панель для IQOS ILUMA i - Chill Blue для IQOS ILUMA i.',
  6300,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-panel/chill-blue.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Синий","colorVariantName":"Chill Blue","line":"Панель для IQOS ILUMA i","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#AAD5FD"}'::jsonb
),
(
  'panel-dlya-iqos-iluma-i-vivid-blue-1020',
  'Панель для IQOS ILUMA i - Vivid Blue',
  'Официальный аксессуар Панель для IQOS ILUMA i - Vivid Blue для IQOS ILUMA i.',
  6300,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-panel/vivid-blue.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Синий","colorVariantName":"Vivid Blue","line":"Панель для IQOS ILUMA i","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#C4EBEA"}'::jsonb
),
(
  'iqos-iluma-i-silikonovyy-chekhol-serene-pink-1021',
  'IQOS ILUMA i Силиконовый чехол - Serene Pink',
  'Официальный аксессуар IQOS ILUMA i Силиконовый чехол - Serene Pink для IQOS ILUMA i.',
  4200,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-silicone-sleeve/serene-pink.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Розовый","colorVariantName":"Serene Pink","line":"IQOS ILUMA i Силиконовый чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#CF447F"}'::jsonb
),
(
  'iqos-iluma-i-silikonovyy-chekhol-wise-violet-1022',
  'IQOS ILUMA i Силиконовый чехол - Wise Violet',
  'Официальный аксессуар IQOS ILUMA i Силиконовый чехол - Wise Violet для IQOS ILUMA i.',
  4200,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-silicone-sleeve/wise-violet.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Фиолетовый","colorVariantName":"Wise Violet","line":"IQOS ILUMA i Силиконовый чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#97A1D7"}'::jsonb
),
(
  'iqos-iluma-i-one-plus-chekhol-majestic-purple-1023',
  'IQOS ILUMA i ONE PLUS Чехол - Majestic Purple',
  'Официальный аксессуар IQOS ILUMA i ONE PLUS Чехол - Majestic Purple для IQOS ILUMA i ONE.',
  3900,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-one-plus-sleeve/majestic-purple.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Фиолетовый","colorVariantName":"Majestic Purple","line":"IQOS ILUMA i ONE PLUS Чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#4E3D7D"}'::jsonb
),
(
  'iqos-iluma-i-one-plus-chekhol-mystical-grey-1024',
  'IQOS ILUMA i ONE PLUS Чехол - Mystical Grey',
  'Официальный аксессуар IQOS ILUMA i ONE PLUS Чехол - Mystical Grey для IQOS ILUMA i ONE.',
  3900,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-one-plus-sleeve/mystical-grey.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","colorVariantName":"Mystical Grey","line":"IQOS ILUMA i ONE PLUS Чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#464C56"}'::jsonb
),
(
  'iqos-iluma-i-one-plus-chekhol-serene-blue-1025',
  'IQOS ILUMA i ONE PLUS Чехол - Serene Blue',
  'Официальный аксессуар IQOS ILUMA i ONE PLUS Чехол - Serene Blue для IQOS ILUMA i ONE.',
  3900,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-one-plus-sleeve/serene-blue.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Синий","colorVariantName":"Serene Blue","line":"IQOS ILUMA i ONE PLUS Чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#7497AA"}'::jsonb
),
(
  'iqos-iluma-i-one-silikonovyy-chekhol-bold-ruby-1026',
  'IQOS ILUMA i ONE Силиконовый чехол - Bold Ruby',
  'Официальный аксессуар IQOS ILUMA i ONE Силиконовый чехол - Bold Ruby для IQOS ILUMA i ONE.',
  3500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-one-silicone-sleeve/bold-ruby.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Красный","colorVariantName":"Bold Ruby","line":"IQOS ILUMA i ONE Силиконовый чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#A93437"}'::jsonb
),
(
  'iqos-iluma-i-one-silikonovyy-chekhol-charming-blue-1027',
  'IQOS ILUMA i ONE Силиконовый чехол - Charming Blue',
  'Официальный аксессуар IQOS ILUMA i ONE Силиконовый чехол - Charming Blue для IQOS ILUMA i ONE.',
  3500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-one-silicone-sleeve/charming-blue.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Синий","colorVariantName":"Charming Blue","line":"IQOS ILUMA i ONE Силиконовый чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#0C2961"}'::jsonb
),
(
  'iqos-iluma-i-one-silikonovyy-chekhol-delicate-blue-1028',
  'IQOS ILUMA i ONE Силиконовый чехол - Delicate Blue',
  'Официальный аксессуар IQOS ILUMA i ONE Силиконовый чехол - Delicate Blue для IQOS ILUMA i ONE.',
  3500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-one-silicone-sleeve/delicate-blue.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Синий","colorVariantName":"Delicate Blue","line":"IQOS ILUMA i ONE Силиконовый чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#60ACAD"}'::jsonb
),
(
  'iqos-iluma-i-one-silikonovyy-chekhol-majestic-purple-1029',
  'IQOS ILUMA i ONE Силиконовый чехол - Majestic Purple',
  'Официальный аксессуар IQOS ILUMA i ONE Силиконовый чехол - Majestic Purple для IQOS ILUMA i ONE.',
  3500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-one-silicone-sleeve/majestic-purple.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Фиолетовый","colorVariantName":"Majestic Purple","line":"IQOS ILUMA i ONE Силиконовый чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#804DBB"}'::jsonb
),
(
  'iqos-iluma-i-one-silikonovyy-chekhol-mysterious-purple-1030',
  'IQOS ILUMA i ONE Силиконовый чехол - Mysterious Purple',
  'Официальный аксессуар IQOS ILUMA i ONE Силиконовый чехол - Mysterious Purple для IQOS ILUMA i ONE.',
  3500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-one-silicone-sleeve/mysterious-purple.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Фиолетовый","colorVariantName":"Mysterious Purple","line":"IQOS ILUMA i ONE Силиконовый чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#412A3F"}'::jsonb
),
(
  'iqos-iluma-i-one-silikonovyy-chekhol-wishful-yellow-1031',
  'IQOS ILUMA i ONE Силиконовый чехол - Wishful Yellow',
  'Официальный аксессуар IQOS ILUMA i ONE Силиконовый чехол - Wishful Yellow для IQOS ILUMA i ONE.',
  3500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-i-one-silicone-sleeve/wishful-yellow.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Золотой","colorVariantName":"Wishful Yellow","line":"IQOS ILUMA i ONE Силиконовый чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#D1C05D"}'::jsonb
),
(
  'premium-nabor-kolets-iqos-iluma-nabor-kolets-iqos-iluma-celebrate-1032',
  'Премиум набор колец IQOS ILUMA - Набор колец IQOS ILUMA - Celebrate',
  'Официальный аксессуар Премиум набор колец IQOS ILUMA - Набор колец IQOS ILUMA - Celebrate для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/premium-ring-set/celebrate.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Золотой","colorVariantName":"Набор колец IQOS ILUMA - Celebrate","line":"Премиум набор колец IQOS ILUMA","type":"Колпачки","compatibility":"IQOS ILUMA i","hex":"linear-gradient(135deg, #898C8D 0%, #00AFAD 50%, #8D8BC3 100%)"}'::jsonb
),
(
  'premium-nabor-kolets-iqos-iluma-nabor-kolets-iqos-iluma-emanate-1033',
  'Премиум набор колец IQOS ILUMA - Набор колец IQOS ILUMA - Emanate',
  'Официальный аксессуар Премиум набор колец IQOS ILUMA - Набор колец IQOS ILUMA - Emanate для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/premium-ring-set/emanate-1.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/premium-ring-set/emanate-2.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Зеленый","colorVariantName":"Набор колец IQOS ILUMA - Emanate","line":"Премиум набор колец IQOS ILUMA","type":"Колпачки","compatibility":"IQOS ILUMA i","hex":"linear-gradient(135deg, #D97D7A 0%, #E0DE8E 50%, #52AFCF 100%)"}'::jsonb
),
(
  'premium-nabor-kolets-iqos-iluma-nabor-kolets-iqos-iluma-exhilarate-1034',
  'Премиум набор колец IQOS ILUMA - Набор колец IQOS ILUMA - Exhilarate',
  'Официальный аксессуар Премиум набор колец IQOS ILUMA - Набор колец IQOS ILUMA - Exhilarate для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/premium-ring-set/exhilarate.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Фиолетовый","colorVariantName":"Набор колец IQOS ILUMA - Exhilarate","line":"Премиум набор колец IQOS ILUMA","type":"Колпачки","compatibility":"IQOS ILUMA i","hex":"linear-gradient(135deg, #667E63 0%, #C45964 50%, #CC9450 100%)"}'::jsonb
),
(
  'nabor-kolets-iqos-iluma-energized-1036',
  'Набор колец IQOS ILUMA - Energized',
  'Официальный аксессуар Набор колец IQOS ILUMA - Energized для IQOS ILUMA i.',
  4900,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/ring-set/energized.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","colorVariantName":"Energized","line":"Набор колец IQOS ILUMA","type":"Колпачки","compatibility":"IQOS ILUMA i","hex":"linear-gradient(135deg, #00DADE 0%, #E5B366 50%, #E7E49A 100%)"}'::jsonb
),
(
  'nabor-kolets-iqos-iluma-grounded-1037',
  'Набор колец IQOS ILUMA - Grounded',
  'Официальный аксессуар Набор колец IQOS ILUMA - Grounded для IQOS ILUMA i.',
  4900,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/ring-set/grounded-1.webp', 'https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/ring-set/grounded-2.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","colorVariantName":"Grounded","line":"Набор колец IQOS ILUMA","type":"Колпачки","compatibility":"IQOS ILUMA i","hex":"linear-gradient(135deg, #CFCFD0 0%, #AAC9DC 50%, #BA607D 100%)"}'::jsonb
),
(
  'nabor-kolets-iqos-iluma-sophisticated-1038',
  'Набор колец IQOS ILUMA - Sophisticated',
  'Официальный аксессуар Набор колец IQOS ILUMA - Sophisticated для IQOS ILUMA i.',
  4900,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/ring-set/sophisticated.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","colorVariantName":"Sophisticated","line":"Набор колец IQOS ILUMA","type":"Колпачки","compatibility":"IQOS ILUMA i","hex":"linear-gradient(135deg, #D18F81 0%, #3B87AD 50%, #8C81BF 100%)"}'::jsonb
),
(
  'iqos-iluma-prime-polnyy-chekhol-golden-khaki-1039',
  'IQOS ILUMA PRIME Полный чехол - Golden Khaki',
  'Официальный аксессуар IQOS ILUMA PRIME Полный чехол - Golden Khaki для IQOS ILUMA i PRIME.',
  11300,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/prime-full-sleeve/golden-khaki.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Золотой","colorVariantName":"Golden Khaki","line":"IQOS ILUMA PRIME Полный чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#A4836C"}'::jsonb
),
(
  'iqos-iluma-prime-polnyy-chekhol-iqos-iluma-prime-tkanevyy-polnyy-chekhol-bronze-taupe-1040',
  'IQOS ILUMA PRIME Полный чехол - IQOS ILUMA PRIME Тканевый полный чехол - Bronze Taupe',
  'Официальный аксессуар IQOS ILUMA PRIME Полный чехол - IQOS ILUMA PRIME Тканевый полный чехол - Bronze Taupe для IQOS ILUMA i PRIME.',
  11300,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/prime-full-sleeve/bronze-taupe.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Бежевый","colorVariantName":"IQOS ILUMA PRIME Тканевый полный чехол - Bronze Taupe","line":"IQOS ILUMA PRIME Полный чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#6F7381"}'::jsonb
),
(
  'iqos-iluma-prime-tkanevaya-kryshka-nakladka-bronze-taupe-1041',
  'IQOS ILUMA PRIME Тканевая крышка-накладка - Bronze Taupe',
  'Официальный аксессуар IQOS ILUMA PRIME Тканевая крышка-накладка - Bronze Taupe для IQOS ILUMA i PRIME.',
  8500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/prime-fabric-cover/bronze-taupe.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Бежевый","colorVariantName":"Bronze Taupe","line":"IQOS ILUMA PRIME Тканевая крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#6F7381"}'::jsonb
),
(
  'iqos-iluma-prime-tkanevaya-kryshka-nakladka-indigo-1042',
  'IQOS ILUMA PRIME Тканевая крышка-накладка - Indigo',
  'Официальный аксессуар IQOS ILUMA PRIME Тканевая крышка-накладка - Indigo для IQOS ILUMA i PRIME.',
  8500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/prime-fabric-cover/indigo.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Синий","colorVariantName":"Indigo","line":"IQOS ILUMA PRIME Тканевая крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#3C5767"}'::jsonb
),
(
  'iqos-iluma-prime-tkanevaya-kryshka-nakladka-iqos-iluma-prime-kryshka-nakladka-obsidian-blac-1043',
  'IQOS ILUMA PRIME Тканевая крышка-накладка - IQOS ILUMA PRIME Крышка-накладка - Obsidian Blac',
  'Официальный аксессуар IQOS ILUMA PRIME Тканевая крышка-накладка - IQOS ILUMA PRIME Крышка-накладка - Obsidian Blac для IQOS ILUMA i PRIME.',
  8500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/prime-fabric-cover/obsidian-black.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Черный","colorVariantName":"IQOS ILUMA PRIME Крышка-накладка - Obsidian Blac","line":"IQOS ILUMA PRIME Тканевая крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#1F1F1F"}'::jsonb
),
(
  'iqos-iluma-prime-tkanevaya-kryshka-nakladka-iqos-iluma-prime-perelivayushcheesya-kryshka-nakladka-night-shade-1044',
  'IQOS ILUMA PRIME Тканевая крышка-накладка - IQOS ILUMA PRIME Переливающееся крышка-накладка - Night Shade',
  'Официальный аксессуар IQOS ILUMA PRIME Тканевая крышка-накладка - IQOS ILUMA PRIME Переливающееся крышка-накладка - Night Shade для IQOS ILUMA i PRIME.',
  8500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/prime-fabric-cover/night-shade.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Фиолетовый","colorVariantName":"IQOS ILUMA PRIME Переливающееся крышка-накладка - Night Shade","line":"IQOS ILUMA PRIME Тканевая крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"linear-gradient(135deg, #5D4662 0%, #ADB297 50%, #79958C 100%)"}'::jsonb
),
(
  'iqos-iluma-prime-tkanevaya-kryshka-nakladka-jade-green-1045',
  'IQOS ILUMA PRIME Тканевая крышка-накладка - Jade Green',
  'Официальный аксессуар IQOS ILUMA PRIME Тканевая крышка-накладка - Jade Green для IQOS ILUMA i PRIME.',
  8500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/prime-fabric-cover/jade-green.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Зеленый","colorVariantName":"Jade Green","line":"IQOS ILUMA PRIME Тканевая крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#5F7068"}'::jsonb
),
(
  'iqos-iluma-prime-tkanevaya-kryshka-nakladka-warm-red-1046',
  'IQOS ILUMA PRIME Тканевая крышка-накладка - Warm Red',
  'Официальный аксессуар IQOS ILUMA PRIME Тканевая крышка-накладка - Warm Red для IQOS ILUMA i PRIME.',
  8500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/prime-fabric-cover/warm-red.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Красный","colorVariantName":"Warm Red","line":"IQOS ILUMA PRIME Тканевая крышка-накладка","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#63292F"}'::jsonb
),
(
  'nakladka-dlya-iqos-iluma-prime-bright-blue-1047',
  'Накладка для IQOS ILUMA PRIME - Bright Blue',
  'Официальный аксессуар Накладка для IQOS ILUMA PRIME - Bright Blue для IQOS ILUMA i PRIME.',
  7100,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/prime-overlay/bright-blue.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Синий","colorVariantName":"Bright Blue","line":"Накладка для IQOS ILUMA PRIME","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#788EC0"}'::jsonb
),
(
  'nakladka-dlya-iqos-iluma-prime-bright-coral-1048',
  'Накладка для IQOS ILUMA PRIME - Bright Coral',
  'Официальный аксессуар Накладка для IQOS ILUMA PRIME - Bright Coral для IQOS ILUMA i PRIME.',
  7100,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/prime-overlay/bright-coral.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Розовый","colorVariantName":"Bright Coral","line":"Накладка для IQOS ILUMA PRIME","type":"Чехлы и панели","compatibility":"IQOS ILUMA i PRIME","hex":"#E9908E"}'::jsonb
),
(
  'iqos-iluma-one-silikonovyy-chekhol-claret-red-1049',
  'IQOS ILUMA ONE Силиконовый чехол - Claret Red',
  'Официальный аксессуар IQOS ILUMA ONE Силиконовый чехол - Claret Red для IQOS ILUMA i ONE.',
  3500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/one-silicone-sleeve/claret-red.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Красный","colorVariantName":"Claret Red","line":"IQOS ILUMA ONE Силиконовый чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#E4506E"}'::jsonb
),
(
  'iqos-iluma-one-silikonovyy-chekhol-new-indigo-1050',
  'IQOS ILUMA ONE Силиконовый чехол - New Indigo',
  'Официальный аксессуар IQOS ILUMA ONE Силиконовый чехол - New Indigo для IQOS ILUMA i ONE.',
  3500,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/one-silicone-sleeve/new-indigo.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Синий","colorVariantName":"New Indigo","line":"IQOS ILUMA ONE Силиконовый чехол","type":"Чехлы и панели","compatibility":"IQOS ILUMA i ONE","hex":"#4C5A84"}'::jsonb
),
(
  'alyuminievaya-panel-dlya-iqos-iluma-azure-blue-1051',
  'Алюминиевая панель для IQOS ILUMA - Azure Blue',
  'Официальный аксессуар Алюминиевая панель для IQOS ILUMA - Azure Blue для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-aluminum-panel/azure-blue.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Синий","colorVariantName":"Azure Blue","line":"Алюминиевая панель для IQOS ILUMA","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#8CB2C7"}'::jsonb
),
(
  'alyuminievaya-panel-dlya-iqos-iluma-moss-green-1052',
  'Алюминиевая панель для IQOS ILUMA - Moss Green',
  'Официальный аксессуар Алюминиевая панель для IQOS ILUMA - Moss Green для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-aluminum-panel/moss-green.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Зеленый","colorVariantName":"Moss Green","line":"Алюминиевая панель для IQOS ILUMA","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#ABC9A8"}'::jsonb
),
(
  'alyuminievaya-panel-dlya-iqos-iluma-pebble-grey-1053',
  'Алюминиевая панель для IQOS ILUMA - Pebble Grey',
  'Официальный аксессуар Алюминиевая панель для IQOS ILUMA - Pebble Grey для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-aluminum-panel/pebble-grey.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","colorVariantName":"Pebble Grey","line":"Алюминиевая панель для IQOS ILUMA","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#B0B0B0"}'::jsonb
),
(
  'panel-dlya-iqos-iluma-moss-green-1054',
  'Панель для IQOS ILUMA - Moss Green',
  'Официальный аксессуар Панель для IQOS ILUMA - Moss Green для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-panel/moss-green.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Зеленый","colorVariantName":"Moss Green","line":"Панель для IQOS ILUMA","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#B5D9AD"}'::jsonb
),
(
  'panel-dlya-iqos-iluma-pebble-beige-1055',
  'Панель для IQOS ILUMA - Pebble Beige',
  'Официальный аксессуар Панель для IQOS ILUMA - Pebble Beige для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-panel/pebble-beige.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Бежевый","colorVariantName":"Pebble Beige","line":"Панель для IQOS ILUMA","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#E6DED5"}'::jsonb
),
(
  'panel-dlya-iqos-iluma-pebble-grey-1056',
  'Панель для IQOS ILUMA - Pebble Grey',
  'Официальный аксессуар Панель для IQOS ILUMA - Pebble Grey для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-panel/pebble-grey.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","colorVariantName":"Pebble Grey","line":"Панель для IQOS ILUMA","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#6E7072"}'::jsonb
),
(
  'panel-dlya-iqos-iluma-amber-green-1057',
  'Панель для IQOS ILUMA - Amber Green',
  'Официальный аксессуар Панель для IQOS ILUMA - Amber Green для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-panel/amber-green.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Зеленый","colorVariantName":"Amber Green","line":"Панель для IQOS ILUMA","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#AFCBA0"}'::jsonb
),
(
  'panel-dlya-iqos-iluma-purple-plume-1058',
  'Панель для IQOS ILUMA - Purple Plume',
  'Официальный аксессуар Панель для IQOS ILUMA - Purple Plume для IQOS ILUMA i.',
  5600,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/iluma-panel/purple-plume.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Фиолетовый","colorVariantName":"Purple Plume","line":"Панель для IQOS ILUMA","type":"Чехлы и панели","compatibility":"IQOS ILUMA i","hex":"#C89FD7"}'::jsonb
),
(
  'adapter-pitaniya-dlya-ustroystv-iqos-iluma-1059',
  'Адаптер питания для устройств IQOS ILUMA',
  'Официальный аксессуар Адаптер питания для устройств IQOS ILUMA для Все устройства.',
  4900,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/power-adapter/power-adapter.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","type":"Зарядные устройства","compatibility":"Все устройства","hex":"#EAE8E7"}'::jsonb
),
(
  'plastikovyy-konteyner-zeleny-1060',
  'Пластиковый Контейнер - Зелены',
  'Официальный аксессуар Пластиковый Контейнер - Зелены для IQOS ILUMA i.',
  4200,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/plastic-container/green.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","colorVariantName":"Зелены","line":"Пластиковый Контейнер","type":"Чистка и уход","compatibility":"IQOS ILUMA i","hex":"#818676"}'::jsonb
),
(
  'plastikovyy-konteyner-krasno-korichnevy-1061',
  'Пластиковый Контейнер - Красно-коричневы',
  'Официальный аксессуар Пластиковый Контейнер - Красно-коричневы для IQOS ILUMA i.',
  4200,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/plastic-container/red-brown.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","colorVariantName":"Красно-коричневы","line":"Пластиковый Контейнер","type":"Чистка и уход","compatibility":"IQOS ILUMA i","hex":"#F27B71"}'::jsonb
),
(
  'plastikovyy-konteyner-nezhno-rozovy-1062',
  'Пластиковый Контейнер - Нежно-розовы',
  'Официальный аксессуар Пластиковый Контейнер - Нежно-розовы для IQOS ILUMA i.',
  4200,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/plastic-container/soft-pink.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","colorVariantName":"Нежно-розовы","line":"Пластиковый Контейнер","type":"Чистка и уход","compatibility":"IQOS ILUMA i","hex":"#F2CCB4"}'::jsonb
),
(
  'plastikovyy-konteyner-sini-1063',
  'Пластиковый Контейнер - Сини',
  'Официальный аксессуар Пластиковый Контейнер - Сини для IQOS ILUMA i.',
  4200,
  'accessories',
  true,
  'IQOS',
  ARRAY['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/accessories/plastic-container/blue.webp']::text[],
  '{"isNew":false,"isHit":false,"isExclusive":false}'::jsonb,
  '{"color":"Серый","colorVariantName":"Сини","line":"Пластиковый Контейнер","type":"Чистка и уход","compatibility":"IQOS ILUMA i","hex":"#527A8F"}'::jsonb
);
