-- ============================================================================
-- Migration: trade_in_devices — admin-manageable list of accepted old devices
-- Run in Supabase Dashboard → SQL Editor.
-- ----------------------------------------------------------------------------
-- Reuses the `products` conventions: bigint id, created_at, image text[],
-- RLS with public SELECT + service-role writes. `base_discount` bakes in the
-- former DEFAULT_TRADE_IN_DISCOUNT (1500) so no fallback logic is needed.
-- ============================================================================

create table if not exists public.trade_in_devices (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  device_key text unique not null,               -- stable key, e.g. 'iqos-3-duo'
  name text not null,
  description text,
  image text[],                                  -- same shape as products.image
  base_discount numeric not null default 1500,   -- discount in RUB for this device
  badge text,                                    -- optional label, e.g. 'Популярно'
  is_active boolean not null default true,       -- hide without deleting
  sort_order integer not null default 0          -- display order in the calculator
);

alter table public.trade_in_devices enable row level security;

-- Public read (the calculator lists these); writes go through the service role.
drop policy if exists "Allow public read access" on public.trade_in_devices;
create policy "Allow public read access"
  on public.trade_in_devices
  for select
  to public
  using (true);

-- Seed the accepted devices (idempotent on device_key).
-- Images live in the Supabase Storage 'old-gadgets' bucket as {device_key}.webp.
insert into public.trade_in_devices
  (device_key, name, description, image, base_discount, badge, sort_order)
values
  ('iqos-3-duo',        'IQOS 3 DUO',                          'Легендарное устройство с двойным сеансом',    array['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/old-gadgets/iqos-3-duo.webp'],        2500, 'Популярно', 1),
  ('iqos-originals-duo','IQOS ORIGINALS DUO',                  'Обновлённая версия IQOS 3 DUO',               array['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/old-gadgets/iqos-originals-duo.webp'], 2500, null,        2),
  ('iqos-3-multi',      'IQOS 3 MULTI',                        'Компактное моноустройство',                   array['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/old-gadgets/iqos-3-multi.webp'],      2000, null,        3),
  ('iqos-2-4-plus',     'IQOS 2.4 / 2.4 Plus',                 'Классическая модель IQOS',                    array['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/old-gadgets/iqos-2-4-plus.webp'],     1500, null,        4),
  ('lil-solid-2',       'lil SOLID 2.0',                       'Устройство с нагревательным стержнем',        array['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/old-gadgets/lil-solid-2.webp'],       1800, null,        5),
  ('lil-solid-ez',      'lil SOLID Ez',                        'Компактная версия lil SOLID',                 array['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/old-gadgets/lil-solid-ez.webp'],      1500, null,        6),
  ('glo-hyper-pro',     'Glo Hyper / Pro',                     'Устройства нагрева табака системы Glo',       array['https://sjqoinxhewxxbcczliyl.supabase.co/storage/v1/object/public/old-gadgets/glo-hyper-pro.webp'],     1500, null,        7),
  ('other-device',      'Другая модель / Электронная сигарета','Принимаем устройства любых производителей',   null,                                      1500, null,        8)
on conflict (device_key) do nothing;
